version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 8
    commands:
      - cd express-api-app
      - npm install
  build:
    commands:
      - npm run-script build
artifacts:
  files:
    - '**/*'
  base-directory: 'express-api-app/build'